### ISSUE TITLE
The example code in README.md does not work

### ISSUE THREAD

**Issue by yaojingguo** [DanielXMoore/Hera#12]
The example code in README.md does not work:
```js
Hera = require("hera")
fs = require("fs")

source = fs.readFileSync("cool-grammar.hera")

rules = Hera.parse(source, {
  filename: path
})

// Generate parser.js source code
parserSource = Hera.generate(rules)
fs.writeFile("cool-parser.js", parserSource)
parser = require("./cool-parser")
// or generate parser object
parser = Hera.generate(rules, true)

parser.parse("text that my cool parser should parse")
```

The first problem is the first require. It should be `Hera = require("@danielx/hera")`.
The second problem is that the hera API are outdated. The latest API are tested in https://github.com/DanielXMoore/Hera/blob/main/test/main.coffee.

**Comment by STRd6** [comment]
Fixed in https://github.com/DanielXMoore/Hera/commit/cbf956482fc88328d88e6011254ea123925b6ad1
